---
title: "Final Project"
author: "Gina Krynski"
date: "5/4/2022"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(tree)
library(randomForest)
library(splines)
library(MASS)
library(gbm)
library(kableExtra)
```


## Data cleaning and preparation
```{r, warning=FALSE}
set.seed(05042022)
stellar_obj <- read.csv("star_classification.csv")
stellar_obj <- stellar_obj %>% mutate(class = as.factor(class)) %>% filter(u != -9999)


## Removing ID and date variables:
stellar_obj <- stellar_obj %>% dplyr::select(alpha, delta, u, g, r, i, z, class, redshift)

## Taking random sample
stellar_sample <- sample_n(stellar_obj, size = 10000)

## Splitting into training and testing sets
trainIndex <- sample(1:nrow(stellar_sample), nrow(stellar_sample) * .80)
stellarTraining <- stellar_sample[trainIndex,]
stellarTesting <- stellar_sample[-trainIndex,]
```

## EDA 

### Using Random Forest to look at variable importance
```{r, warning=FALSE}

stellar_forest <- train(class ~. , 
                     data = stellarTraining,
                     importance = T,
                     method="rf",
                     trControl=trainControl("oob"),
                     ntree=100)
stellar_forest
varImp(stellar_forest, scale=FALSE)
plot(varImp(stellar_forest, scale=FALSE))

```

## More Exploratory Plots
```{r}
ggplot(stellar_sample, aes(x=u, y=redshift, color=class)) +
  geom_point() +
  theme_bw() + 
  labs(title="Redshift vs U")

ggplot(stellar_sample, aes(x=u, y=g, color=class)) +
  geom_point() +
  theme_bw() + 
  labs(title="G vs U")

ggplot(stellar_sample, aes(x=u, y=z, color=class)) +
  geom_point() +
  theme_bw() + 
  labs(title="Z vs U ")

ggplot(stellar_sample, aes(x=u, y=delta, color=class)) +
  geom_point() +
  theme_bw() + 
  labs(title="Delta vs U")

```
## Model 1: LDA
```{r, warning=FALSE}
# Train the model
lda_mod <- train(class ~ ., data=stellarTraining, method="lda",
                trControl=trainControl(method="cv",number=5),
                         preProcess = c("center", "scale"))
print(lda_mod)

# Test predictions
stellarTesting$pred_class_lda <- predict(lda_mod, newdata=stellarTesting)

# Misclassification rate
misclass_rate_lda <- mean(stellarTesting$pred_class_lda != stellarTesting$class)
```


## Model 2: PLS Classification
```{r, warning=FALSE}
pls_mod <- plsr <- train(class ~ .,
                   data=stellarTraining,
                   method="pls", 
                   preProcess=c("center", "scale"),
                   trControl = trainControl(method="cv", 5),
                   tuneGrid=data.frame(ncomp=1:8)) 
print(pls_mod)

# Test predictions
stellarTesting$pred_class_pls <- predict(pls_mod, newdata=stellarTesting)

# Misclassification rate
misclass_rate_pls <- mean(stellarTesting$pred_class_pls != stellarTesting$class)
```

## Model 3: Random Forest
```{r, warning=FALSE}
random_forest_model <- train(class~.,
                   data=stellarTraining,
                   method="rf",
                   trControl=trainControl("oob"), 
                   tuneGrid=data.frame(mtry=1:10),
                   ntree=200) 

random_forest_model

# Test predictions
stellarTesting$pred_class_rf <- predict(random_forest_model, newdata=stellarTesting)

# Misclassification rate
misclass_rate_rf <- mean(stellarTesting$pred_class_rf != stellarTesting$class)

```

## Model 4:Support Vector Classifier
```{r, warning=FALSE}
svc <- train(class ~.,
             data=stellarTraining,
             method="svmLinear",
             trControl=trainControl("cv", number=5),
             tuneGrid=data.frame(C=c(0.1,1,10)))


svc$bestTune
print(svc)

# Test predictions
stellarTesting$pred_class_svc <- predict(svc, newdata=stellarTesting)

# Misclassification rate
misclass_rate_svc <- mean(stellarTesting$pred_class_svc != stellarTesting$class)
```

## Model Comparison
```{r, warning=FALSE}
Model <- c("LDA", "PLS Classification", "Random Forest", "SVC")
Missclassification <- c(misclass_rate_lda, misclass_rate_pls, misclass_rate_rf, misclass_rate_svc)
model_comparison <- data_frame(Model, Missclassification)
model_comparison %>% kbl() %>% kable_styling()


```

## Final Model Description
```{r}
random_forest_model$finalModel

```







